services:
  - type: web
    name: messenger
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_URL
        sync: false